### ISSUE TITLE
[Question] How do you access metadata about the Cache from a prefetcher function?

### ISSUE THREAD

**Issue by sanjana879** [hpsresearchgroup/scarab#110]
Hi, I'm trying to implement a prefetching policy in Scarab and I need metadata about the cache like the number of sets/ways the cache has. I see the Cache object has that information as a field, but where is the Cache instance I can get that information from?

**Comment by siavashzk** [comment]
To answer these kind of questions, I suggest searching the source code for examples of how that is done elsewhere in the code. For example, to find some use cases of getting cache instances, I simply searched for Cache (case sensitive, whole word) and found a few matching lines:

Cache*   l1_cache = &mem->uncores[ic->proc_id].l1->cache;

Cache*       dcache  = &(cmp_model.dcache_stage[proc_id].dcache)

  Icache_Stage* ic = &(cmp_model.icache_stage[proc_id]);
  Cache*      icache  = &(ic->icache);


For your specific question of getting cache configuration params, it's probably easier to just read the global parameters. For example: DCACHE_SIZE, DCACHE_ASSOC, DCACHE_LINE_SIZE for Dcache.
