### ISSUE TITLE
[Question] Decoder: Redirect on btb_miss and !taken

### ISSUE THREAD

**Issue by hlitz** [hpsresearchgroup/scarab#115]
In line 215 in decoder.c, direct branches that suffer from a btb_miss that are not taken trigger a redirect. I believe this is a bug. If a direct branch is not taken (fall through path) then scarab should not care about whether there was a BTB miss. Since rarely/never taken branches are not put into the BTB this may lead to inaccuracies. The suggested fix is to also check whether the branch was taken. This also applies to indirect branches in line 227.

 // since it is not indirect, redirect the input stream if it was a btb
      // miss
      if(op->oracle_info.btb_miss && !bf) {

adding @5surim @petervbraun to this thread

**Comment by spruett** [comment]
Try enabling `PERFECT_NT_BTB`. 

This knob makes it so that a predicted not-taken conditional direct branch is never a btb miss. And branches that are not btb misses do not install their targets in the BTB, so I think it is the behavior you are looking for.

**Comment by hlitz** [comment]
Thanks Stephen, that solves it.
