### ISSUE TITLE
[Question]About Wrong Path Execution

### ISSUE THREAD

**Issue by JohnKon98** [hpsresearchgroup/scarab#137]
Hello,
I wanted to ask if Scarab does take a checkpoint on a mispredict while executing in the wrong path. (Mispredict under Mispredict)
Thanks - Ioannis

**Comment by chestercai1995** [comment]
I am assuming you are asking if scarab is able to recover to a later mispredict that is under another unresolved mispredict. 

The answer to your question is yes. Under a wrong path, Scarab saves the changes between each instruction (which effectively is a checkpoint). This allows Scarab to roll back to any particular point during the wrong path, including a mispredicted branch under the wrong path.

Let me know if this is not what you are looking for.

**Comment by JohnKon98** [comment]
That's what I was looking for,
Thank you for your reply.
