### ISSUE TITLE
[Question] Assertion failure when running gcc in SPEC2017 IntSpeed

### ISSUE THREAD

**Issue by yunjinw** [hpsresearchgroup/scarab#139]
Hello,

I am a PhD student working with Prof. Anand Sivasubramaniam at Penn State. I was trying to simulate benchmarks in SPEC2017 Integer Speed by first generating checkpoints according to docs/run_spec17.md and then running the checkpoints with "python3 bin/scarab_batch.py </path/to/scarab_batch_profile.py> --run". The config file I used is src/PARAMS.kaby_lake.

All benchmarks except for gcc were simulated successfully. For gcc, I encountered error messages saying that "thread.c:86: ASSERT FAILED (P=0  O=42250155  I=32048837  C=23808191):  Scarab's recovery addr 0x573b3a does not match frontend's recovery addr 0xbba910" for <ref1, ckpt4> and "thread.c:86: ASSERT FAILED (P=0  O=259514256  I=198999152  C=143214723):  Scarab's recovery addr 0x573b54 does not match frontend's recovery addr 0xbba910" for <ref2, ckpt2>.

Gcc was simulated successfully with "--fetch_off_path_ops 0" though. Could you please take a look at this problem? Thanks a lot!

Best,
Yunjin

**Comment by chestercai1995** [comment]
Can you give us your checkpoint information? starting instruction and length of the checkpoint would be good.

In addition, can you run it with "--debug_cycle_start 1 --debug_cycle_stop 23808200 --debug_inst_start 32000000 --debug_inst_stop 33000000 --debug_icache_stage 1 --debug_bp 1"?

**Comment by yunjinw** [comment]
Here is the checkpoint info.
**gcc_17_s_ref1_ckpt4**
simulation-region-start-icount = 259400004752, simulation-region-end-icount = 259600004753, length = 200000002
**gcc_17_s_ref2_ckpt2**
simulation-region-start-icount = 487200008960, simulation-region-end-icount = 487400008966, length = 200000007

**Comment by chestercai1995** [comment]
Closing this. Already replied to this in an email.
