### ISSUE TITLE
[Question] Proper documentation for running SPEC 17

### ISSUE THREAD

**Issue by sawansib** [hpsresearchgroup/scarab#140]
Hello!

I wanted to ask if I can get some documentation or anything else to find out how I can run the SPEC 17 application. I have already generated the checkpoints and the descriptor.def but can't find a way to run them on scarab.

Sawan

**Comment by chestercai1995** [comment]
Hi Sawan,
    After generating the checkpoints, you can run them with scarab_batch.py under bin directory. The scarab batch file takes a jobfile as an argument. We have provided an example jobfile  here: scarab/utils/qsort/example_scarab_batch_jobfile.py

Chester

**Comment by sawansib** [comment]
Great! Thank you.

Sawan
