### ISSUE TITLE
Compile fails on pin_fe_lib_opt

### ISSUE THREAD

**Issue by nblei** [hpsresearchgroup/scarab#23]
**Describe the bug**
Compilation fails on Makefile line 253: pin_fe_lib_opt 

**To Reproduce**
1. cd src && make

Building 'dep/Linux/opt/bp/gshare.dd'
Building 'dep/Linux/opt/bp/hybridgp.dd'
Building 'dep/Linux/opt/bp/tagescl.dd'
Building 'dep/Linux/opt/power/power_scarab_config.dd'
Building 'dep/Linux/opt/frontend/pin_trace_read.dd'
Building 'dep/Linux/opt/frontend/pin_exec_driven_fe.dd'
Building 'dep/Linux/opt/ramulator.dd'
Building 'dep/Linux/opt/bp/bp_conf.d, bp/bp_conf'
Building 'dep/Linux/opt/bp/bp.d, bp/bp'
Building 'dep/Linux/opt/bp/bp_targ_mech.d, bp/bp_targ_mech'
Building 'dep/Linux/opt/prefetcher/pref_stridepc.d, prefetcher/pref_stridepc'
Building 'dep/Linux/opt/prefetcher/pref_stream.d, prefetcher/pref_stream'
Building 'dep/Linux/opt/prefetcher/l2way_pref.d, prefetcher/l2way_pref'
Building 'dep/Linux/opt/prefetcher/pref_stride.d, prefetcher/pref_stride'
Building 'dep/Linux/opt/prefetcher/pref_phase.d, prefetcher/pref_phase'
Building 'dep/Linux/opt/prefetcher/pref_markov.d, prefetcher/pref_markov'
Building 'dep/Linux/opt/prefetcher/pref_ghb.d, prefetcher/pref_ghb'
Building 'dep/Linux/opt/prefetcher/l2markv_pref.d, prefetcher/l2markv_pref'
Building 'dep/Linux/opt/prefetcher/l2l1pref.d, prefetcher/l2l1pref'
Building 'dep/Linux/opt/prefetcher/pref_2dc.d, prefetcher/pref_2dc'
Building 'dep/Linux/opt/prefetcher/pref_common.d, prefetcher/pref_common'
Building 'dep/Linux/opt/prefetcher/stream_pref.d, prefetcher/stream_pref'
Building 'dep/Linux/opt/dvfs/dvfs.d, dvfs/dvfs'
Building 'dep/Linux/opt/dvfs/perf_pred.d, dvfs/perf_pred'
Building 'dep/Linux/opt/dvfs/power_pred.d, dvfs/power_pred'
Building 'dep/Linux/opt/power/power_intf.d, power/power_intf'
Building 'dep/Linux/opt/debug/pipeview.d, debug/pipeview'
Building 'dep/Linux/opt/debug/debug_print.d, debug/debug_print'
Building 'dep/Linux/opt/debug/memview.d, debug/memview'
Building 'dep/Linux/opt/frontend/frontend_intf.d, frontend/frontend_intf'
Building 'dep/Linux/opt/frontend/frontend.d, frontend/frontend'
Building 'dep/Linux/opt/frontend/pin_trace_fe.d, frontend/pin_trace_fe'
Building 'dep/Linux/opt/libs/cache_lib.d, libs/cache_lib'
Building 'dep/Linux/opt/libs/malloc_lib.d, libs/malloc_lib'
Building 'dep/Linux/opt/libs/hash_lib.d, libs/hash_lib'
Building 'dep/Linux/opt/libs/port_lib.d, libs/port_lib'
Building 'dep/Linux/opt/libs/list_lib.d, libs/list_lib'
Building 'dep/Linux/opt/isa/isa.d, isa/isa'
Building 'dep/Linux/opt/globals/utils.d, globals/utils'
Building 'dep/Linux/opt/globals/enum.d, globals/enum'
Building 'dep/Linux/opt/cache_part.d, cache_part'
Building 'dep/Linux/opt/dcache_stage.d, dcache_stage'
Building 'dep/Linux/opt/stat_trace.d, stat_trace'
Building 'dep/Linux/opt/thread.d, thread'
Building 'dep/Linux/opt/trigger.d, trigger'
Building 'dep/Linux/opt/map.d, map'
Building 'dep/Linux/opt/exec_stage.d, exec_stage'
Building 'dep/Linux/opt/memory.d, memory'
Building 'dep/Linux/opt/cmp_model.d, cmp_model'
Building 'dep/Linux/opt/op_pool.d, op_pool'
Building 'dep/Linux/opt/node_stage.d, node_stage'
[ -f gitrev ] || touch gitrev
echo '"'c23ee41'"' | cmp -s gitrev - || echo '"'c23ee41'"' > gitrev
Building 'dep/Linux/opt/version.d, version'
Building 'dep/Linux/opt/map_stage.d, map_stage'
Building 'dep/Linux/opt/dumb_model.d, dumb_model'
Building 'dep/Linux/opt/optimizer2.d, optimizer2'
Building 'dep/Linux/opt/addr_trans.d, addr_trans'
Building 'dep/Linux/opt/statistics.d, statistics'
Building 'dep/Linux/opt/exec_ports.d, exec_ports'
Building 'dep/Linux/opt/icache_stage.d, icache_stage'
Building 'dep/Linux/opt/decode_stage.d, decode_stage'
Building 'dep/Linux/opt/main.d, main'
Building 'dep/Linux/opt/cmp_model_support.d, cmp_model_support'
Building 'dep/Linux/opt/packet_build.d, packet_build'
Building 'dep/Linux/opt/param_parser.d, param_parser'
Building 'dep/Linux/opt/sim.d, sim'
Building 'dep/Linux/opt/freq.d, freq'
Building 'dep/Linux/opt/mem_req.d, mem_req'
Building 'dep/Linux/opt/stat_mon.d, stat_mon'
[ -f gitrev ] || touch gitrev
echo '"'c23ee41'"' | cmp -s gitrev - || echo '"'c23ee41'"' > gitrev
make SCARAB_DIR=/magnetic/src/scarab/src --directory pin/pin_lib
make[1]: Entering directory '/magnetic/src/scarab/src/pin/pin_lib'
make dir
make[2]: Entering directory '/magnetic/src/scarab/src/pin/pin_lib'
mkdir -p obj
make[2]: Leaving directory '/magnetic/src/scarab/src/pin/pin_lib'
make archive
make[2]: Entering directory '/magnetic/src/scarab/src/pin/pin_lib'
g++ -MT obj/message_queue_interface_lib.o -MMD -MP -MF obj/message_queue_interface_lib.d -std=c++14 -O3  -fno-inline -funroll-loops -Werror -I/magnetic/src/scarab/src -DNO_DEBUG -Wall -Wunused -Wno-long-long -Wpointer-arith -Werror -D_REENTRANT   -fPIC -c -o obj/message_queue_interface_lib.o message_queue_interface_lib.cc
g++ -MT obj/pin_scarab_common_lib.o -MMD -MP -MF obj/pin_scarab_common_lib.d -std=c++14 -O3  -fno-inline -funroll-loops -Werror -I/magnetic/src/scarab/src -DNO_DEBUG -Wall -Wunused -Wno-long-long -Wpointer-arith -Werror -D_REENTRANT   -fPIC -c -o obj/pin_scarab_common_lib.o pin_scarab_common_lib.cc
gcc -MT obj/uop_generator.o -MMD -MP -MF obj/uop_generator.d -std=gnu99 -O3  -funroll-loops -Werror -I/magnetic/src/scarab/src -DNO_DEBUG -Wall -Wunused -Wmissing-prototypes -Wmissing-declarations -Wno-long-long -Wpointer-arith -Wimplicit -Werror -D_REENTRANT   -fPIC -c -o obj/uop_generator.o uop_generator.c
ar rcs obj/libpin_fe.a obj/message_queue_interface_lib.o obj/pin_scarab_common_lib.o obj/uop_generator.o
make[2]: Leaving directory '/magnetic/src/scarab/src/pin/pin_lib'
make[1]: Leaving directory '/magnetic/src/scarab/src/pin/pin_lib'
make SCARAB_DIR=/magnetic/src/scarab/src rollback --directory pin/pin_exec
make[1]: Entering directory '/magnetic/src/scarab/src/pin/pin_exec'
makefile:13: ../Config/makefile.config: No such file or directory
makefile:15: /Config/makefile.default.rules: No such file or directory
make[1]: *** No rule to make target '/Config/makefile.default.rules'.  Stop.
make[1]: Leaving directory '/magnetic/src/scarab/src/pin/pin_exec'
Makefile:253: recipe for target 'pin_fe_lib_opt' failed
make: *** [pin_fe_lib_opt] Error 2

**Expected behavior**
Expected to compile succesfully

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS (Bionic Beaver)

**Comment by siavashzk** [comment]
Before compiling, you have to download Intel PIN 3.5 (link in [system requirements](https://github.com/hpsresearchgroup/scarab/blob/master/docs/system_requirements.md)).

After downloading and extracting PIN 3.5, in your environment variable, set PIN_ROOT to the pin directory.

I'll update compiling instructions to state this.

**Comment by nblei** [comment]
Thanks, siavashzk.

This fixed the initial issue, but revealed a different one.

The link to PIN 3.5 leads me to an "Access Denied" page from Intel (despite my developer account with them), so I instead downloaded PIN 3.13,  3.11, and 2.14 from https://software.intel.com/en-us/articles/pin-a-binary-instrumentation-tool-downloads 

Both lead to a cascade of compilation issues beginning with:

```
In file included from /magnetic/bin/pin-3.11-97998-g7ecce2dac-gcc-linux/extras/components/include/util/scoped-ptr.hpp:20:0,
                 from /magnetic/bin/pin-3.11-97998-g7ecce2dac-gcc-linux/extras/components/include/util.hpp:36,
                 from /magnetic/bin/pin-3.11-97998-g7ecce2dac-gcc-linux/extras/components/include/atomic/exponential-backoff.hpp:20,
                 from /magnetic/bin/pin-3.11-97998-g7ecce2dac-gcc-linux/extras/components/include/atomic/ops.hpp:20,
                 from /magnetic/bin/pin-3.11-97998-g7ecce2dac-gcc-linux/extras/components/include/atomic.hpp:51,
                 from /magnetic/bin/pin-3.11-97998-g7ecce2dac-gcc-linux/source/include/pin/level_base.PLH:77,
                 from /magnetic/bin/pin-3.11-97998-g7ecce2dac-gcc-linux/source/include/pin/pin.H:21,
                 from rollback.cpp:33:
./assert.h:58:0: error: "ASSERT" redefined [-Werror]
```

**Comment by siavashzk** [comment]
Hmm, looks like we need to update the PIN download link as well.

This link should work for 3.5
https://software.intel.com/en-us/articles/program-recordreplay-toolkit

After clicking on the download link and accepting the terms, you should be able to download 3.5. It works fine for me without having to log in.

We plan to update to 3.11 or 3.13, but it requires some work in fixing the conflicts in the global namespace.

**Comment by nblei** [comment]
Thanks.

Still looks like there are macro collisions between PIN 3.5 and scarab.

I'll work on fixing this in a bit.

**Comment by siavashzk** [comment]
I just submitted a commit that removes a redundant assert.h file. My speculation is that somehow your compiler environment included that instead of the assert.h in PinCRT. 

If this does not solve your problem, please feel free to open the issue again.
