### ISSUE TITLE
[Question] Query about BTB update implementation

### ISSUE THREAD

**Issue by takhandipu** [hpsresearchgroup/scarab#93]
Let me paste the code snippet from [bp.c:600](https://github.com/hpsresearchgroup/scarab/blob/8a85d2bb6a0b396cf412d03b73f22ad885e42237/src/bp/bp.c#L600) first which will set up the context for the question:
```
/******************************************************************************/
/* bp_target_known_op: called on cf ops when the real target is known
   (either decode time or execute time) */

void bp_target_known_op(Bp_Data* bp_data, Op* op) {
  ASSERT(bp_data->proc_id, bp_data->proc_id == op->proc_id);
  ASSERT(bp_data->proc_id, op->table_info->cf_type);

  // if it was a btb miss, it is time to write it into the btb
  if(op->oracle_info.btb_miss)
    bp_data->bp_btb->update_func(bp_data, op);

  // special case updates
  switch(op->table_info->cf_type) {
    case CF_ICALL:  // fall through
    case CF_IBR:
      if(ENABLE_IBP) {
        if(IBTB_OFF_PATH_WRITES || !op->off_path) {
          bp_data->bp_ibtb->update_func(bp_data, op);
        }
      }
      break;
    default:
      break;  // do nothing
  }
}
```
Based on the source code, the current bpu implementation will update (or add if not present) a BTB entry even though the branch has already been identified (decoded) as indirect call/jump or return. If `ENABLE_CRS` and `ENABLE_IBP` both are `FALSE`, this update makes sense. However, why would current bpu implementation update and waste BTB entries when `ENABLE_IBP` and `ENABLE_CRS` are `TRUE`?

**Comment by spruett** [comment]
Hi, thanks for the question. 

I think you are correct about a slight inaccuracy in Scarab. To my knowledge, what is typically done here is there are actually two structures: let's call them the Branch Buffer and the Target Buffer. The Branch Buffer holds static information about the branch (e.g., that it is a branch, what kind of branch it is call/return/indirect/etc, and any other static information about the branch that may assist with fetch or prediction). The Target Buffer holds the target of the branch in the case of direct branches. 

An indirect branch would require a Branch Buffer entry, but not a Target Buffer entry (as the target would be supplied by the iBTB structure). 

Now in Scarab, we only model one structure: the Branch Target Buffer (BTB). This means when we allocate the required BTB entry to track static branch information (things the Branch Buffer would have tracked in my earlier example) we are also allocating a target entry, which is technically a waste of space. 

I believe from a performance modeling perspective, there is nothing to be concerned about here. However, with added complexity, the BTB could be split into two structures to improve space efficiency. 

Does this answer your question?

**Comment by takhandipu** [comment]
It does. Thanks for your answer. That also explains why IPC falls when I add the following check before the BTB entry update even with `ENABLE_CRS` and `ENABLE_IBP`.
```
if(op->oracle_info.btb_miss && (op->table_info->cf_type == CF_CBR || op->table_info->cf_type == CF_CALL || op->table_info->cf_type == CF_BR))
    bp_data->bp_btb->update_func(bp_data, op);
```
Seems like branch static information is much more important than few wasted bytes in the BTB. I was assuming that branch static information is stored in the branch predictor instead of BTB. That is because, Scarab already uses `cf_type` (one of the static information) to determine whether to look at BTB, IBTB, or handle special case syscall (as seen in the code snippets below). Thanks anyways for your answer.
![image](https://user-images.githubusercontent.com/7850376/109363752-4df21580-785b-11eb-9818-3179846a26ad.png)
and
![image](https://user-images.githubusercontent.com/7850376/109363789-6104e580-785b-11eb-9afb-80f2a830d97a.png)
