### ISSUE TITLE
[Question] Scarab frontend for CBP traces

### ISSUE THREAD

**Issue by nlbrown2** [hpsresearchgroup/scarab#94]
Hello,

If I wanted to run scarab on traces not from Pin or of the `ctype_pin_inst` format, such as the traces from [CBP](https://www.jilp.org/cbp2016/), would scarab support those? From what I can tell, the current frontend infrastructure is highly dependent on the `ctype_pin_inst` format, whose fields like `size`, `is_*` and `pin_iclass` suggest a strong need to have the traces come with some kind of information on opcode / instruction bytes. Does scarab support running traces without such rich information? If so, how might one go about making that happen?

**Comment by spruett** [comment]
Hi, thanks for the question. 

I am not 100% sure I understand your question, so I am going to do my best here, but let me know if I missed the mark. 

**Can we run CBP traces on Scarab?**
Currently we have no frontend that can read CBP traces. That being said, I am not sure I see why you would need one. CBP already has a simulator that is capable of running their traces fully, I think using their infrastructure would be best if you want to run CBP traces. 

**Can we run traces that have less information on Scarab?**
Yes and no. Yes, Scarab could be modified to not *need* all the information that is currently required in the structs you mention; however, this would not be a good use of Scarab. Scarab needs all of the information in it's traces/executables to provide accurate simulations. 

For example, if we modified Scarab to support CBP traces, it would ultimately result in the same simulator environment that the CBP simulator already provides. CBP traces only contain branches, and do not contain the loads, stores, and various other instructions that make running Scarab useful.

In general, there are benefits to running reduced traces (faster simulations, etc), but that is ultimately not the goal of Scarab. 

**Can I run Scarab traces/executables on branch predictors submitted to CBP?**
This is the reverse of the question that I think you asked, but I couldn't help but include the information as well. Scarab DOES have an interface to easily plug and play any of the branch predictors from CBP 2016. Older predictors (from CBP 2014 and earlier) could also likely be run with very little effort, but there are some slight inconsistencies between the 2016 interface and earlier interfaces. See `src/bp/cbp_to_scarab.*` for more information on this. 

Let me know if this does not answer your question.

**Comment by spruett** [comment]
I am going to close this issue due to inactivity.
